### ISSUE TITLE
lineup2() plan needs better diagnostics, especially when it does not succeed

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#1044]
When using the `lineup2()` plan, users have reported that the plan appears to run successfully and print a report of the peak statistics.  Yet the motor has not been moved to the expected position after `lineup2()` finishes.  The only possible diagnostic is to supply a `signals_stats=obj` kwarg to the plan, then check that after the scan.

How does a user know if `lineup2()` has not succeeded?  What reason(s)?

**Comment by prjemian** [comment]
Here's a simple test code:

```py
from apstools.callbacks.scan_signal_statistics import SignalStatsCallback
from apstools.plans import lineup2
from bluesky.callbacks.best_effort import BestEffortCallback
from ophyd.sim import motor, noisy_det
import bluesky
import matplotlib.pyplot as plt
import ophyd

plt.ion()
RE = bluesky.RunEngine()
bec = BestEffortCallback()
RE.subscribe(bec)
flat = ophyd.Signal(name="flat", value=10)
stats = SignalStatsCallback()

signal = noisy_det
RE(lineup2([signal], motor, -1, 1, 11, nscans=1, signal_stats=stats))
cen = stats._registers[signal.name].centroid
in_pos = abs(motor.position - cen) <= 0.001
stats.report()
print(f"{in_pos=!r}")
```

**Comment by prjemian** [comment]
Problem is here: https://github.com/BCDA-APS/apstools/blob/e9780ed838d95aa726ffda14e40f95b5e0d0da76/apstools/plans/alignment.py#L444

**Comment by prjemian** [comment]
user error message:

<details>

```py
 File "/share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/bluesky/preprocessors.py", line 134, in plan_mutator
    msg = plan_stack[-1].send(ret)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/bluesky/preprocessors.py", line 907, in fly_during_wrapper
    return (yield from plan2)
            ^^^^^^^^^^^^^^^^
  File "/share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/bluesky/preprocessors.py", line 181, in plan_mutator
    raise ex
  File "/share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/bluesky/preprocessors.py", line 134, in plan_mutator
    msg = plan_stack[-1].send(ret)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/bluesky/preprocessors.py", line 181, in plan_mutator
    raise ex
  File "/share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/bluesky/preprocessors.py", line 134, in plan_mutator
    msg = plan_stack[-1].send(ret)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/bluesky/instrument/plans/axis_tuning.py", line 96, in tune_mr
    yield from _tune_base_(m_stage.r, md=md)
  File "/home/beams/USAXS/bluesky/instrument/plans/axis_tuning.py", line 72, in _tune_base_
    uuids = yield from axis.tune(md=md)     #note: the tune method comes from usaxs_motor_devices, TunableEpicsMotor, which uses lineup2
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/bluesky/instrument/devices/usaxs_motor_devices.py", line 109, in tune
    return (yield from _inner())
            ^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/bluesky/instrument/devices/usaxs_motor_devices.py", line 107, in _inner
    yield from self.post_tune_hook()
TypeError: 'NoneType' object is not iterable


class FilterBank(Device):
    """
    A single module of filters (12-blades).

    .. index:: Ophyd Device; FilterBank

    EXAMPLES::

        pfilter = FilterBank("ioc:", name="pfilter", bank="FL1")

    :see: 
    """

 
    class TransmDerivedSignal(DerivedSignal):
        def forward(self, value):
            return 1/value      
         
        #def inverse(self, value):
        #    return 1/value
        

    fPos = FormattedComponent(EpicsSignal, "{prefix}{_bank}:sortedIndex", kind="config")
    #control = FormattedComponent(EpicsSignalRO, "{prefix}bank{_bank}", string=True, kind="config")
    #bits = FormattedComponent(EpicsSignalRO, "{prefix}bitFlag{_bank}", kind="config")
    attenuation = FormattedComponent(EpicsSignalRO, "{prefix}{_bank}:attenuation_actual", kind="config")
    transmission = TransmDerivedSignal(derived_from=attenuation, name="transmission", metadata=None)

    def __init__(self, prefix, bank=None, **kwargs):
        self._bank = bank
        super().__init__(prefix, **kwargs)

ile /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/ophyd/signal.py:630, in DerivedSignal.__init__(self=<class 'instrument.devices.filters.FilterBank.TransmDerivedSignal'> instance, derived_from=FormattedComponent(EpicsSignalRO, '{prefix}{_bank}:attenuation_actual', kind='config'), write_access=None, name='transmission', parent=None, **kwargs={'metadata': None})
    626     self._metadata_keys = getattr(derived_from, "metadata_keys", None)
    627     # And failing that, they are the defaults from all signals
    629 super().__init__(
--> 630     name=name, parent=parent, metadata=derived_from.metadata, **kwargs
        derived_from = FormattedComponent(EpicsSignalRO, '{prefix}{_bank}:attenuation_actual', kind='config')
        parent = None
        name = 'transmission'
        kwargs = {'metadata': None}
    631 )
    633 self._derived_from = derived_from
    635 self._allow_writes = write_access is not False

AttributeError: 'FormattedComponent' object has no attribute 'metadata'
```

</details>

**Comment by prjemian** [comment]
- https://github.com/APS-USAXS/bluesky/issues/9

**Comment by prjemian** [comment]
The problem is that `stats.stddev_y` for this clearly distinguished peak is comparable to the peak height.  Switched the computation to: `value = stats.max_y / stats.min_y`

**Comment by prjemian** [comment]
Occasionally have received `ValueError: math domain error`

<details>

```py
In [25]: RE(lineup2([signal], motor, -8, 1, 19, nscans=1, signal_stats=stats))
    ...: cen = stats._registers[signal.name].centroid
    ...: in_pos = abs(motor.position - cen) <= 0.001
    ...: print(f"{in_pos=!r}")
    ...: stats.report(); trim_plot_by_name(5, "noisy_det vs motor")


Transient Scan ID: 27     Time: 2024-11-22 18:30:30
Persistent Unique Scan ID: '82dd2d33-b1c0-442f-b7f1-f6962c23ff08'
New stream: 'primary'
+-----------+------------+------------+------------+
|   seq_num |       time |      motor |  noisy_det |
+-----------+------------+------------+------------+
|         1 | 18:30:30.6 |     -8.322 |     -0.047 |
|         2 | 18:30:30.6 |     -7.822 |     -0.070 |
|         3 | 18:30:30.6 |     -7.322 |     -0.001 |
|         4 | 18:30:30.6 |     -6.822 |      0.081 |
|         5 | 18:30:30.7 |     -6.322 |     -0.041 |
|         6 | 18:30:30.7 |     -5.822 |      0.058 |
|         7 | 18:30:30.7 |     -5.322 |     -0.044 |
|         8 | 18:30:30.7 |     -4.822 |     -0.025 |
|         9 | 18:30:30.7 |     -4.322 |      0.077 |
|        10 | 18:30:30.7 |     -3.822 |      0.023 |
Run aborted
Traceback (most recent call last):
  File "/share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/bluesky/run_engine.py", line 1605, in _run
    msg = self._plan_stack[-1].send(resp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/apstools/plans/alignment.py", line 480, in lineup2
    target = get_x_by_feature()
             ^^^^^^^^^^^^^^^^^^
  File "/share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/apstools/plans/alignment.py", line 435, in get_x_by_feature
    peak_too_wide = too_wide(stats)
                    ^^^^^^^^^^^^^^^
  File "/share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/apstools/plans/alignment.py", line 465, in too_wide
    fwhm = stats.sigma * factor_fwhm
           ^^^^^^^^^^^
  File "/share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/pysumreg/sum_registers.py", line 298, in sigma
    return math.sqrt((self.XXY - self.centroid * self.XY) / self.Y)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: math domain error
|        11 | 18:30:30.7 |     -3.322 |      0.054 |
|        12 | 18:30:30.7 |     -2.822 |      0.098 |
|        13 | 18:30:30.8 |     -2.322 |      0.018 |
|        14 | 18:30:30.8 |     -1.822 |      0.098 |
|        15 | 18:30:30.8 |     -1.322 |      0.420 |
|        16 | 18:30:30.8 |     -0.822 |      0.721 |
|        17 | 18:30:30.8 |     -0.322 |      0.930 |
|        18 | 18:30:30.8 |      0.178 |      1.079 |
|        19 | 18:30:30.8 |      0.678 |      0.764 |
+-----------+------------+------------+------------+
generator rel_scan ['82dd2d33'] (scan num: 27)



---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[25], line 1
----> 1 RE(lineup2([signal], motor, -8, 1, 19, nscans=1, signal_stats=stats))
      2 cen = stats._registers[signal.name].centroid
      3 in_pos = abs(motor.position - cen) <= 0.001

File /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/bluesky/run_engine.py:973, in RunEngine.__call__(self, *args, **metadata_kw)
    969         self._blocking_event.set()
    971     self._task_fut.add_done_callback(set_blocking_event)
--> 973 plan_return = self._resume_task(init_func=_build_task)
    975 if self._interrupted:
    976     raise RunEngineInterrupted(self.pause_msg) from None

File /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/bluesky/run_engine.py:1109, in RunEngine._resume_task(self, init_func)
   1106 # if the main task exception is not None, re-raise
   1107 # it (unless it is a canceled error)
   1108 if exc is not None and not isinstance(exc, _RunEnginePanic):
-> 1109     raise exc
   1110 # Only try to get a result if there wasn't an error,
   1111 # (other than a cancelled error)
   1112 if exc is None:

File /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/bluesky/run_engine.py:1751, in RunEngine._run(self)
   1749     exit_reason = str(err)
   1750     self.log.exception("Run aborted")
-> 1751     raise err
   1752 finally:
   1753     if not exit_reason:

File /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/bluesky/run_engine.py:1605, in RunEngine._run(self)
   1602 # The normal case of clean operation
   1603 else:
   1604     try:
-> 1605         msg = self._plan_stack[-1].send(resp)
   1606     # We have exhausted the top generator
   1607     except StopIteration:
   1608         # pop the dead generator go back to the top

File /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/apstools/plans/alignment.py:480, in lineup2(detectors, mover, rel_start, rel_end, points, peak_factor, width_factor, feature, nscans, signal_stats, md)
    477 yield from _inner()  # Run the scan.
    478 nscans -= 1
--> 480 target = get_x_by_feature()
    481 if target is None:
    482     nscans = 0  # Nothing found, no point scanning again.

File /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/apstools/plans/alignment.py:435, in lineup2.<locals>.get_x_by_feature()
    433 stats = principal_signal_stats()
    434 peak_strong = strong_peak(stats)
--> 435 peak_too_wide = too_wide(stats)
    436 print(f"{feature=!r}")
    437 if peak_strong and not peak_too_wide:

File /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/apstools/plans/alignment.py:465, in lineup2.<locals>.too_wide(stats)
    463 try:
    464     x_range = stats.max_x - stats.min_x
--> 465     fwhm = stats.sigma * factor_fwhm
    466     return fwhm > width_factor * x_range
    467 except ZeroDivisionError:  # not enough samples

File /share1/bluesky/conda_envs/bluesky_2024_3/lib/python3.11/site-packages/pysumreg/sum_registers.py:298, in SummationRegisters.sigma(self)
    283 @property
    284 def sigma(self):
    285     r"""
    286     The y-weighted variance (:math:`\sigma_c^2`) of :math:`(x, y)`.
    287 
   (...)
    296     See: :meth:`centroid`
    297     """
--> 298     return math.sqrt((self.XXY - self.centroid * self.XY) / self.Y)

ValueError: math domain error

In [26]: 

```

</details>

**Comment by prjemian** [comment]
For this `math domain error`,

> must call the [`.clear()`](https://prjemian.github.io/pysumreg/sum_registers.html#pysumreg.sum_registers.SummationRegisters.clear) method before each new use where `stats` is an instance of `SummationRegisters()`.

**Comment by prjemian** [comment]
Looking at an overhaul here, switching from `PySumReg` to `numpy` for the statistical analyses.  Will deprecate PySumReg use (and `.registers` attribute) in favor of new `.analysis` attribute with new statistics computation.

- [x] Refactor the decision if peak was found.  
- [x] Engineer (and document) a way for caller to know if peak was found and if not, why.
- [ ] Refactor so peak statistics can be reported as additional stream in the run.  (Replace `rel_scan()` plan with custom.)
- [ ] Refactor unit tests.
  - [x] using `.analysis`
  - [ ] Replace EPICS-based `pvoigt` signal with pure Python (goal: decrease testing time of `lineup2()` by 100x)

**Comment by prjemian** [comment]
> ... reported as additional stream ...

Must replace `rel_scan()` plan with custom plan.  The heart of [`bp.scan_nd()`](https://github.com/bluesky/bluesky/blob/92d2633127e33e51aa1d1b109c80503e74bbe0e0/src/bluesky/plans.py#L1162-L1170) provides the basis:

```py
    @bpp.stage_decorator(list(detectors) + motors)
    @bpp.run_decorator(md=_md)
    def inner_scan_nd():
        if predeclare:
            yield from bps.declare_stream(*motors, *detectors, name="primary")
        for step in list(cycler):
            yield from per_step(detectors, step, pos_cache)
        # TODO: write analysis to `"peak_analysis"` stream

    return (yield from inner_scan_nd())
```

**Comment by prjemian** [comment]
The last two items on the [checklist above](https://github.com/BCDA-APS/apstools/issues/1044#issuecomment-2501347777) can be pushed to a new issue.

**Comment by prjemian** [comment]
Improving on the peak width validation [above](https://github.com/BCDA-APS/apstools/issues/1044#issuecomment-2495140515),  this code:

```py
abs((stats.max_y - stats.min_y) / (stats.mean_y - stats.min_y)) > peak_factor
```

which is still subject to a ZeroDivisionError (which means this peak "width" is not acceptable).
