### ISSUE TITLE
bluesky_snapshot_viewer : Exception in Tkinter callback

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#110]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/apstools/snapshot.py", line 261, in receiver
    callbacks.SnapshotReport().print_report(header)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/apstools/callbacks.py", line 171, in print_report
    print("snapshot:", header.start["iso8601"])
KeyError: 'iso8601'
```

**Comment by prjemian** [comment]
Failed on the 21:26:55 entry

![Clipboard02](https://user-images.githubusercontent.com/2279984/54788256-6469ae00-4bfc-11e9-87a2-d036c42cb762.jpg)

**Comment by prjemian** [comment]
failure was actually in the search of databroker for the scan with given uid due to improper search syntax
