### ISSUE TITLE
PyPI package does not install dependencies

### ISSUE THREAD

**Issue by mrakitin** [BCDA-APS/apstools#129]
It looks like the package published at PyPI (https://pypi.org/project/apstools/) does not install the dependencies (`databroker`, etc.). The reason is an empty `install_requires` field in https://github.com/BCDA-APS/apstools/blob/f6aa51556e0a2faf3fa3f93530e40b657ba86001/setup.py#L35 caused by this block of code
https://github.com/BCDA-APS/apstools/blob/f6aa51556e0a2faf3fa3f93530e40b657ba86001/apstools/__init__.py#L28-L29

As far as I understand from the comment there, the conda recipe tries to install the deps from PyPI. To avoid this, change this line https://github.com/BCDA-APS/apstools/blob/f6aa51556e0a2faf3fa3f93530e40b657ba86001/conda-recipe/meta.yaml#L26 to something like
```
 script: python setup.py install --single-version-externally-managed --record=record.txt
```
(like in [bluesky's recipe](https://github.com/NSLS-II/lightsource2-recipes/blob/1cfbdc74d239d4c188abdd564648c120e6eaf636/recipes-tag/bluesky/meta.yaml#L13)) or even to the conda-forge recommended way http://conda-forge.org/docs/maintainer/adding_pkgs.html#use-pip.

**Comment by prjemian** [comment]
Thanks for that.  What about the `record.txt` file?

**Comment by mrakitin** [comment]
I think it's a legacy way of installing packages (which we still use) to keep the record of egg-files. See e.g. https://mythinkpond.com/2016/09/30/uninstall-python-eggs-that-you-installed-using-setup-py for the details. I changed the recipe in the PR to use pip (based on [conda-build's documentation](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#defining-metadata-meta-yaml)).

**Comment by mrakitin** [comment]
pip-package also misses `` `pyRestTable`:
```py
$ bluesky_snapshot -h
/home/mrakitin/conda_envs/apstools/lib/python3.6/site-packages/databroker/databroker.py:42: UserWarning: There was a error loading '_legacy_config': ModuleNotFoundError("No module named 'pymongo'",)
  warn("There was a error loading {!r}: {!r}".format(SPECIAL_NAME, exc))
Traceback (most recent call last):
  File "/home/mrakitin/conda_envs/apstools/bin/bluesky_snapshot", line 7, in <module>
    from apstools.snapshot import snapshot_cli
  File "/home/mrakitin/conda_envs/apstools/lib/python3.6/site-packages/apstools/snapshot.py", line 51, in <module>
    from . import utils as APS_utils
  File "/home/mrakitin/conda_envs/apstools/lib/python3.6/site-packages/apstools/utils.py", line 38, in <module>
    import pyRestTable
ModuleNotFoundError: No module named 'pyRestTable'
```

Also, `pymongo` wasn't found. It's an [optional dependency](https://github.com/NSLS-II/databroker/blob/171c98543d7a06deee2d8518e54d4709653880b3/setup.py#L18-L20) of databroker, so `__install_requires__` may need to be updated with `'databroker[all]'`.

After those 2 deps were installed manually, I noticed that some plans were imported from bluesky. I think it should be a dependency as well.

**Comment by mrakitin** [comment]
```py
$ bluesky_snapshot -h
Traceback (most recent call last):
  File "/home/mrakitin/conda_envs/apstools/bin/bluesky_snapshot", line 7, in <module>
    from apstools.snapshot import snapshot_cli
  File "/home/mrakitin/conda_envs/apstools/lib/python3.6/site-packages/apstools/snapshot.py", line 51, in <module>
    from . import utils as APS_utils
  File "/home/mrakitin/conda_envs/apstools/lib/python3.6/site-packages/apstools/utils.py", line 44, in <module>
    from .plans import run_in_thread
  File "/home/mrakitin/conda_envs/apstools/lib/python3.6/site-packages/apstools/plans.py", line 34, in <module>
    from bluesky import preprocessors as bpp
ModuleNotFoundError: No module named 'bluesky'
```

**Comment by mrakitin** [comment]
OK, and now ophyd:
```py
$ bluesky_snapshot -h
Traceback (most recent call last):
  File "/home/mrakitin/conda_envs/apstools/bin/bluesky_snapshot", line 7, in <module>
    from apstools.snapshot import snapshot_cli
  File "/home/mrakitin/conda_envs/apstools/lib/python3.6/site-packages/apstools/snapshot.py", line 51, in <module>
    from . import utils as APS_utils
  File "/home/mrakitin/conda_envs/apstools/lib/python3.6/site-packages/apstools/utils.py", line 44, in <module>
    from .plans import run_in_thread
  File "/home/mrakitin/conda_envs/apstools/lib/python3.6/site-packages/apstools/plans.py", line 38, in <module>
    import ophyd
ModuleNotFoundError: No module named 'ophyd'
```

**Comment by mrakitin** [comment]
I'd recommend placing all the deps to `requirements.txt` and read/parse this file in apstools/apstools/__init__.py, as now the requirements in 2 places are different, and `requirements.txt` is simply ignored.

**Comment by prjemian** [comment]
This is a great recommendation!
