### ISSUE TITLE
make general method to export JSON datasets

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#137]
In #136, code was developed to export datasets from the USAXS instrument into a JSON text file.  Generalize that code and contribute to `apstools.utils`.

**Comment by prjemian** [comment]
ZIP the export file.

**Comment by prjemian** [comment]
Could be a command-line application, *also*.

**Comment by prjemian** [comment]
travis-ci reports it cannot import pyRestTable
It is downloaded and installed but `conda list` does not show it.  Something must be off in the travis config.

**Comment by prjemian** [comment]
skipping the command-line entry-point (for now)

**Comment by prjemian** [comment]
travis-ci reports success but the logs say different:

```
======================================================================
ERROR: test_newfile_exists (test_filewriter.Test_SpecWriterCallback)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_filewriter.py", line 146, in test_newfile_exists
    specwriter.newfile(filename=testfile)
  File "tests/../apstools/filewriters.py", line 531, in newfile
    from spec2nexus.spec import SpecDataFile
ModuleNotFoundError: No module named 'spec2nexus'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "tests/test_filewriter.py", line 151, in test_newfile_exists
    self.assertFalse(raised, "file exists")
UnboundLocalError: local variable 'raised' referenced before assignment
```
