### ISSUE TITLE
travis-ci fails: cannot import name 'schema_validators'

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#170]
This job failed in [travis-ci](https://travis-ci.org/BCDA-APS/apstools/jobs/543895971).

```
1.10s$ coverage run tests/
Traceback (most recent call last):
  File "tests/__main__.py", line 34, in <module>
    runner.run(suite())
  File "tests/__main__.py", line 17, in suite
    import test_export_json
  File "tests/test_export_json.py", line 20, in <module>
    from apstools.utils import json_export, json_import
  File "tests/../apstools/utils.py", line 54, in <module>
    from .plans import run_in_thread
  File "tests/../apstools/plans.py", line 36, in <module>
    from bluesky import preprocessors as bpp
  File "/home/travis/miniconda/envs/travis-3.6/lib/python3.6/site-packages/bluesky/__init__.py", line 6, in <module>
    from .run_engine import RunEngine
  File "/home/travis/miniconda/envs/travis-3.6/lib/python3.6/site-packages/bluesky/run_engine.py", line 15, in <module>
    from event_model import DocumentNames, schema_validators
ImportError: cannot import name 'schema_validators'
The command "coverage run tests/" exited with 1.
```

**Comment by prjemian** [comment]
This was installed: `    event-model-1.9.0          |           py36_0          33 KB  lightsource2-tag`
But this v1.10.0 is now tagged and that provides the missing [`schema_validators`](https://github.com/bluesky/event-model/blob/d6d52608166eb3bf2f87b80b586f5cdac9f9d543/docs/source/release-history.rst).

Time to update the requirements.

**Comment by prjemian** [comment]
Still fails with

    ERROR: jsonschema 3.0.1 has requirement attrs>=17.4.0, but you'll have attrs 16.3.0 which is incompatible.

note it installed eventmodel 1.0-9 against the requirements

the main part of this branch is good.  resolve this issue after the PR is merged

**Comment by prjemian** [comment]
[Success!](https://travis-ci.org/BCDA-APS/apstools/jobs/543908039)
