### ISSUE TITLE
ValidationError during RE(run_command_file("sample_example.txt"))

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#188]
While working on documentation of `RE()` call in #184 (final step), received an exception trace ending with this error message:

    ValidationError: 'matplotlib.numpy' does not match any of the regexes: '^([^./]+)$'

<details>
<summary>exception trace</summary>
<p>

```
In [3]: RE(APS_plans.run_command_file("/home/mintadmin/Documents/eclipse/apstools/docs/source/resources/sample_example.txt"))
Command file: /home/mintadmin/Documents/eclipse/apstools/docs/source/resources/sample_example.txt
====== ========== ===========================================================
line # action     parameters                                                 
====== ========== ===========================================================
3      step_scan  5.07, 8.3, 0.0, Water Blank, deionized                     
4      other_scan 5.07, 8.3, 0.0, Water Blank, deionized                     
8      this       line, will, not, be, recognized, by, execute_command_list()
====== ========== ===========================================================

file line 3: step_scan 5.07  8.3   0.0  "Water Blank, deionized"
[E 16:31:33.720 run_engine:1264] Run aborted                                                                                                                  
    Traceback (most recent call last):                                                                                                                        
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/run_engine.py", line 1153, in _run
        msg = self._plan_stack[-1].send(resp)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 1294, in __call__
        return (yield from plan)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 1147, in baseline_wrapper
        return (yield from plan)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 790, in monitor_during_wrapper
        return (yield from plan2)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 848, in fly_during_wrapper
        return (yield from plan2)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/home/mintadmin/Documents/eclipse/apstools/apstools/plans.py", line 532, in run_command_file
        yield from _COMMAND_HANDLER_(filename, commands)
      File "/tmp/me.py", line 65, in execute_command_list
        yield from step_scan(*args, md=_md)
      File "/tmp/me.py", line 21, in step_scan
        yield from bp.scan([scaler], motor, 0, 180, 360, md=md)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/plans.py", line 849, in scan
        per_step=per_step, md=_md))
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/plans.py", line 750, in scan_nd
        return (yield from inner_scan_nd())
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/utils.py", line 1011, in dec_inner
        return (yield from plan)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 939, in stage_wrapper
        return (yield from finalize_wrapper(inner(), unstage_devices()))
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 500, in finalize_wrapper
        ret = yield from plan
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 937, in inner
        return (yield from plan)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/utils.py", line 1011, in dec_inner
        return (yield from plan)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 316, in run_wrapper
        rs_uid = yield from open_run(md)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/plan_stubs.py", line 713, in open_run
        return (yield Msg('open_run', **(md or {})))
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
        msg = plan_stack[-1].throw(exception)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/utils.py", line 136, in single_gen
        return (yield msg)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
        msg = plan_stack[-1].throw(exception)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/utils.py", line 136, in single_gen
        return (yield msg)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/run_engine.py", line 1211, in _run
        new_response = yield from coro(msg)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/run_engine.py", line 1374, in _open_run
        yield from self.emit(DocumentNames.start, doc)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/asyncio/coroutines.py", line 212, in coro
        res = func(*args, **kw)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/run_engine.py", line 2323, in emit
        _validate(doc, schemas[name])
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
        cls(schema, *args, **kwargs).validate(instance)
      File "/home/mintadmin/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
        raise error
    jsonschema.exceptions.ValidationError: 'matplotlib.numpy' does not match any of the regexes: '^([^./]+)$'
    
    Failed validating 'additionalProperties' in schema['patternProperties']['^([^./]+)$']:
        {'additionalProperties': False,
         'patternProperties': {'^([^./]+)$': {'$ref': '#/definitions/data_type'}},
         'title': 'data_type'}
    
    On instance['versions']:
        {'apstools': '1.1.6+82.gdab7989.dirty',
         'bluesky': '1.5.2',
         'databroker': '0.13.0',
         'epics': '3.3.3',
         'matplotlib.numpy': '1.10.0',
         'numpy': '1.12.1',
         'ophyd': '1.3.3',
         'pyRestTable': '2019.0508.1',
         'spec2nexus': '2020.0.0'}



[E 16:31:33.738 run_engine:1301] Failed to close run None.
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
/tmp/me.py in <module>()
----> 1 RE(APS_plans.run_command_file("/home/mintadmin/Documents/eclipse/apstools/docs/source/resources/sample_example.txt"))

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    754                     # it (unless it is a canceled error)
    755                     if exc is not None:
--> 756                         raise exc
    757 
    758             if self._interrupted:

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
   1263             self._reason = str(err)
   1264             self.log.exception("Run aborted")
-> 1265             raise err
   1266         finally:
   1267             # Some done_callbacks may still be alive in other threads.

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
   1151                     else:
   1152                         try:
-> 1153                             msg = self._plan_stack[-1].send(resp)
   1154                         # We have exhausted the top generator
   1155                         except StopIteration:

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1292         plan = monitor_during_wrapper(plan, self.monitors)
   1293         plan = baseline_wrapper(plan, self.baseline)
-> 1294         return (yield from plan)

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1145     if not devices:
   1146         # no-op
-> 1147         return (yield from plan)
   1148     else:
   1149         return (yield from plan_mutator(plan, insert_baseline))

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    788     plan1 = plan_mutator(plan, insert_after_open)
    789     plan2 = plan_mutator(plan1, insert_before_close)
--> 790     return (yield from plan2)
    791 
    792 

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    846     plan1 = plan_mutator(plan, insert_after_open)
    847     plan2 = plan_mutator(plan1, insert_before_close)
--> 848     return (yield from plan2)
    849 
    850 

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

~/Documents/eclipse/apstools/apstools/plans.py in run_command_file(filename, md)
    530     """
    531     commands = get_command_list(filename)
--> 532     yield from _COMMAND_HANDLER_(filename, commands)
    533 
    534 

/tmp/me.py in execute_command_list(filename, commands, md)
     63         action = action.lower()
     64         if action == "step_scan":
---> 65             yield from step_scan(*args, md=_md)
     66         elif action == "other_scan":
     67             yield from other_scan(*args, md=_md)

/tmp/me.py in step_scan(sx, sy, thickness, title, md)
     19     )
     20     yield from prepare_detector("scintillator")
---> 21     yield from bp.scan([scaler], motor, 0, 180, 360, md=md)
     22 
     23 def other_scan(sx, sy, thickness, title, md={}):

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/plans.py in scan(detectors, num, per_step, md, *args)
    847 
    848     return (yield from scan_nd(detectors, full_cycler,
--> 849                                per_step=per_step, md=_md))
    850 
    851 

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/plans.py in scan_nd(detectors, cycler, per_step, md)
    748             yield from per_step(detectors, step, pos_cache)
    749 
--> 750     return (yield from inner_scan_nd())
    751 
    752 

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1009                 plan = gen_func(*inner_args, **inner_kwargs)
   1010                 plan = wrapper(plan, *args, **kwargs)
-> 1011                 return (yield from plan)
   1012             return dec_inner
   1013         return dec

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in stage_wrapper(plan, devices)
    937         return (yield from plan)
    938 
--> 939     return (yield from finalize_wrapper(inner(), unstage_devices()))
    940 
    941 

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in finalize_wrapper(plan, final_plan, pause_for_debug)
    498     cleanup = True
    499     try:
--> 500         ret = yield from plan
    501     except GeneratorExit:
    502         cleanup = False

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in inner()
    935     def inner():
    936         yield from stage_devices()
--> 937         return (yield from plan)
    938 
    939     return (yield from finalize_wrapper(inner(), unstage_devices()))

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1009                 plan = gen_func(*inner_args, **inner_kwargs)
   1010                 plan = wrapper(plan, *args, **kwargs)
-> 1011                 return (yield from plan)
   1012             return dec_inner
   1013         return dec

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in run_wrapper(plan, md)
    314         metadata to be passed into the 'open_run' message
    315     """
--> 316     rs_uid = yield from open_run(md)
    317 
    318     def except_plan(e):

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/plan_stubs.py in open_run(md)
    711     :func:`bluesky.plans_stubs.close_run`
    712     """
--> 713     return (yield Msg('open_run', **(md or {})))
    714 
    715 

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     75             # if we have a stashed exception, pass it along
     76             try:
---> 77                 msg = plan_stack[-1].throw(exception)
     78             except StopIteration as e:
     79                 # discard the exhausted generator

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/utils.py in single_gen(msg)
    134         the input message
    135     '''
--> 136     return (yield msg)
    137 
    138 

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     75             # if we have a stashed exception, pass it along
     76             try:
---> 77                 msg = plan_stack[-1].throw(exception)
     78             except StopIteration as e:
     79                 # discard the exhausted generator

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/utils.py in single_gen(msg)
    134         the input message
    135     '''
--> 136     return (yield msg)
    137 
    138 

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
   1209                         # exceptions (coming in via throw) can be
   1210                         # raised
-> 1211                         new_response = yield from coro(msg)
   1212 
   1213                     # special case `CancelledError` and let the outer

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/run_engine.py in _open_run(self, msg)
   1372 
   1373         doc = dict(uid=self._run_start_uid, time=ttime.time(), **md)
-> 1374         yield from self.emit(DocumentNames.start, doc)
   1375         self.log.debug("Emitted RunStart (uid=%r)", doc['uid'])
   1376         yield from self._reset_checkpoint_state_coro()

~/Apps/anaconda/envs/bluesky/lib/python3.6/asyncio/coroutines.py in coro(*args, **kw)
    210         @functools.wraps(func)
    211         def coro(*args, **kw):
--> 212             res = func(*args, **kw)
    213             if (base_futures.isfuture(res) or inspect.isgenerator(res) or
    214                 isinstance(res, CoroWrapper)):

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/bluesky/run_engine.py in emit(self, name, doc)
   2321     def emit(self, name, doc):
   2322         "Process blocking callbacks and schedule non-blocking callbacks."
-> 2323         _validate(doc, schemas[name])
   2324         self.dispatcher.process(name, doc)
   2325 

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/jsonschema/validators.py in validate(instance, schema, cls, *args, **kwargs)
    539         cls = validator_for(schema)
    540     cls.check_schema(schema)
--> 541     cls(schema, *args, **kwargs).validate(instance)

~/Apps/anaconda/envs/bluesky/lib/python3.6/site-packages/jsonschema/validators.py in validate(self, *args, **kwargs)
    128         def validate(self, *args, **kwargs):
    129             for error in self.iter_errors(*args, **kwargs):
--> 130                 raise error
    131 
    132         def is_type(self, instance, type):

ValidationError: 'matplotlib.numpy' does not match any of the regexes: '^([^./]+)$'

Failed validating 'additionalProperties' in schema['patternProperties']['^([^./]+)$']:
    {'additionalProperties': False,
     'patternProperties': {'^([^./]+)$': {'$ref': '#/definitions/data_type'}},
     'title': 'data_type'}

On instance['versions']:
    {'apstools': '1.1.6+82.gdab7989.dirty',
     'bluesky': '1.5.2',
     'databroker': '0.13.0',
     'epics': '3.3.3',
     'matplotlib.numpy': '1.10.0',
     'numpy': '1.12.1',
     'ophyd': '1.3.3',
     'pyRestTable': '2019.0508.1',
     'spec2nexus': '2020.0.0'}

In [4]: 
```

</p>
</details>

**Comment by prjemian** [comment]
offending configuration lines:

    from matplotlib import __version__numpy__ as mpl_np_version
    RE.md['versions']['matplotlib.numpy'] = mpl_np_version
    del mpl_np_version

Do not create a metadata dictionary key with a "." in it!  Do this instead:

    RE.md['versions']['matplotlib_numpy'] = mpl_np_version

Also, do not forget to delete the offending key.

    del RE.md['versions']['matplotlib.numpy']

**Comment by prjemian** [comment]
The tipoff to solve this problem was in these lines of the exception trace:

```
    jsonschema.exceptions.ValidationError: 'matplotlib.numpy' does not match any of the regexes: '^([^./]+)$'
    
    Failed validating 'additionalProperties' in schema['patternProperties']['^([^./]+)$']:
        {'additionalProperties': False,
         'patternProperties': {'^([^./]+)$': {'$ref': '#/definitions/data_type'}},
         'title': 'data_type'}
    
    On instance['versions']:
        {'apstools': '1.1.6+82.gdab7989.dirty',
         'bluesky': '1.5.2',
         'databroker': '0.13.0',
         'epics': '3.3.3',
         'matplotlib.numpy': '1.10.0',
         'numpy': '1.12.1',
         'ophyd': '1.3.3',
         'pyRestTable': '2019.0508.1',
         'spec2nexus': '2020.0.0'}
```

The text `matplotlib.numpy` **only** appears in the ipython startup configuration where we have added software version information to the RunEngine's metadata dictionary for diagnostic purposes.  The key was easy to find in the local repository using: `git grep matplotlib.numpy` which pointed directly to the problem definition.
