### ISSUE TITLE
DOCS build error on RTD

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#189]
See https://readthedocs.org/projects/apstools/builds/9328141/

<details>
<summary>details</summary>
<p>

```
 Running Sphinx v2.1.2
loading translations [en]... done
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 24 source files that are out of date
updating environment: 24 added, 0 changed, 0 removed
reading sources... [  4%] applications/index
reading sources... [  8%] applications/snapshot
reading sources... [ 12%] examples/_nscan
reading sources... [ 16%] examples/_plan_catalog
reading sources... [ 20%] examples/_run_command_list
reading sources... [ 25%] examples/_specfile
reading sources... [ 29%] examples/_tuneaxis
reading sources... [ 33%] examples/downloads
reading sources... [ 37%] examples/index
reading sources... [ 41%] examples/source
reading sources... [ 45%] index
reading sources... [ 50%] license
reading sources... [ 54%] source/_callbacks
reading sources... [ 58%] source/_devices
reading sources... [ 62%] source/_filewriters
reading sources... [ 66%] source/_plans
reading sources... [ 70%] source/_signals
reading sources... [ 75%] source/_suspenders
reading sources... [ 79%] source/_utils
reading sources... [ 83%] source/index
reading sources... [ 87%] source/synApps/_busy
reading sources... [ 91%] source/synApps/_sscan
reading sources... [ 95%] source/synApps/_swait
reading sources... [100%] source/synApps/index

/home/docs/checkouts/readthedocs.org/user_builds/apstools/checkouts/latest/docs/source/examples/_run_command_list.rst:266: WARNING: Title level inconsistent:

Prepare the RE
^^^^^^^^^^^^^^^
/home/docs/checkouts/readthedocs.org/user_builds/apstools/checkouts/latest/docs/source/examples/_run_command_list.rst:317: WARNING: Title level inconsistent:

Run the command file
^^^^^^^^^^^^^^^^^^^^^
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  4%] applications/index
writing output... [  8%] applications/snapshot
writing output... [ 12%] examples/_nscan
writing output... [ 16%] examples/_plan_catalog
writing output... [ 20%] examples/_run_command_list

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/sphinx/highlighting.py", line 137, in get_lexer
    lexer = guess_lexer(source)
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/pygments/lexers/__init__.py", line 309, in guess_lexer
    for lexer in _iter_lexerclasses():
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/pygments/lexers/__init__.py", line 234, in _iter_lexerclasses
    for lexer in find_plugin_lexers():
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/pygments/plugin.py", line 55, in find_plugin_lexers
    yield entrypoint.load()
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (prompt-toolkit 1.0.15 (/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages), Requirement.parse('prompt-toolkit<2.1.0,>=2.0.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/sphinx/application.py", line 345, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 319, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 382, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 562, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 573, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/sphinx/builders/html.py", line 644, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/sphinx/writers/html.py", line 59, in translate
    self.document.walkabout(visitor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 1 more time]
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/sphinx/writers/html5.py", line 435, in visit_literal_block
    location=(self.builder.current_docname, node.line), **highlight_args
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/sphinx/highlighting.py", line 167, in highlight_block
    lexer = self.get_lexer(source, lang, opts, force, location)
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/sphinx/highlighting.py", line 139, in get_lexer
    lexer = lexers['none']
KeyError: 'none'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/apstools/conda/latest/lib/python3.6/site-packages/sphinx/highlighting.py", line 139, in get_lexer
    lexer = lexers['none']
KeyError: 'none'
The full traceback has been saved in /tmp/sphinx-err-er1_pqii.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks! 
```

</p>
</details>

These lines (from the trace) in particular:

```
/home/docs/checkouts/readthedocs.org/user_builds/apstools/checkouts/latest/docs/source/examples/_run_command_list.rst:266: WARNING: Title level inconsistent:

Prepare the RE
^^^^^^^^^^^^^^^
/home/docs/checkouts/readthedocs.org/user_builds/apstools/checkouts/latest/docs/source/examples/_run_command_list.rst:317: WARNING: Title level inconsistent:

Run the command file
^^^^^^^^^^^^^^^^^^^^^
```

**Comment by prjemian** [comment]
Need to specify the language for all code blocks.  The lexer is not successful when guessing some times.

**Comment by prjemian** [comment]
[success!](https://readthedocs.org/projects/apstools/builds/9328601/)
