### ISSUE TITLE
What ophyd signal uses this EPICS PV?

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#496]
This is a common question as an instrument package begins to grow.  Users know the EPICS PV but forgot which EPICS signal and then where is it defined.

**Comment by prjemian** [comment]
Works fine but can report on uninitialized area detector plugins during the initial indexing operation, such as:

```python
In [1]: findpv("adsky:HDF1:FilePath_RBV")
Subscription value callback exception (EpicsSignal(read_pv='adsky:image1:ArrayData', name='adsimdet_image_array_data', parent='adsimdet_image', value=array([], dtype=uint8), timestamp=631152000.0, auto_monitor=True, string=False, write_pv='adsky:image1:ArrayData', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/home/mintadmin/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/device.py", line 223, in __get__
    return instance._signals[self.attr]
KeyError: 'shaped_image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mintadmin/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/signal.py", line 608, in _derived_value_callback
    value = self.inverse(value)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/areadetector/base.py", line 107, in inverse
    raise RuntimeError(f"Invalid array size {self.derived_shape}")
RuntimeError: Invalid array size (0, 0, 0)
Out[1]: {'read': ['adsimdet.hdf1.file_path'], 'write': []}

In [2]: findpv("adsky:HDF1:FilePath_RBV")
Out[2]: {'read': ['adsimdet.hdf1.file_path'], 'write': []}

In [3]: findpv("sky:m1.RBV")
Out[3]: {'read': ['m1.user_readback'], 'write': []}

```

**Comment by prjemian** [comment]
Reluctant to release this new feature until a problem such as this is handled better.  Reports such as this one will raise questions.

**Comment by gfabbris** [comment]
Would it be useful to have related `findname`? Where you give an `ophyd` name and it returns the python object?

**Comment by prjemian** [comment]
Not necessarily a unique result so returned value might be different each
time it is called.

**Comment by prjemian** [comment]
@gfabbris : Looks like `findname(ophyd_undotted_name)` will work:

```python
apstools.utils.findpv("ad:image1:ArrayData", ns=ns) = {'read': ['simdet.image.array_data'], 'write': ['simdet.image.array_data']}
apstools.utils.findpv("ad:HDF1:FilePath_RBV", ns=ns) = {'read': ['simdet.hdf1.file_path'], 'write': []}
apstools.utils.findpv("ad:cam1:Acquire", ns=ns) = {'read': [], 'write': ['simdet.cam.acquire']}
apstools.utils.findpv("gp:m1.RBV", ns=ns) = {'read': ['gpm1.user_readback'], 'write': []}
apstools.utils.findname("gpm1_user_setpoint", ns=ns) = 'm1.user_setpoint'
apstools.utils.findname("m1_user_setpoint", ns=ns) = None
apstools.utils.findname("simdet_cam_acquire", ns=ns) = 'simdet.cam.acquire'
apstools.utils.findname("simdet_hdf1_array_size", ns=ns) = 'simdet.hdf1.array_size'
apstools.utils.findname("simdet_image_dim1_sa", ns=ns) = 'simdet.image.array_size.dim1_sa'
apstools.utils.findname("simdet_cam_peak_width_peak_width_y", ns=ns) = 'simdet.cam.peak_width.peak_width_y'
```

Note that to enable testing of this code, it was necessary to allow an optional namespace (`ns`) kwarg.  Here's the namespace used above: `ns = dict(m1=gpm1, simdet=simdet)` which explains why `gpm1_user_setpoint` was found but `m1_user_setpoint` was not.
