### ISSUE TITLE
spec2ophyd fails on config files from 17BM

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#499]
See code in branch [s2o-novelties](https://github.com/BCDA-APS/apstools/tree/s2o-novelties)

```
(bluesky_2021_1) [17bmuser@bm17-bluesky ~]> spec2ophyd /tmp/spec/spec/config | tee ${INSTRUMENT_DIR}/devices/spec.py
Traceback (most recent call last):
  File "/home/beams/17BMUSER/.conda/envs/bluesky_2021_1/bin/spec2ophyd", line 10, in <module>
    sys.exit(main())
  File "/home/beams/17BMUSER/.conda/envs/bluesky_2021_1/lib/python3.8/site-packages/apstools/migration/spec2ophyd.py", line 514, in main
    spec_cfg.read_config()
  File "/home/beams/17BMUSER/.conda/envs/bluesky_2021_1/lib/python3.8/site-packages/apstools/migration/spec2ophyd.py", line 448, in read_config
    motor.setDevice(self.devices)
  File "/home/beams/17BMUSER/.conda/envs/bluesky_2021_1/lib/python3.8/site-packages/apstools/migration/spec2ophyd.py", line 239, in setDevice
    unit, chan = list(map(int, uc_str.split("/")))
ValueError: too many values to unpack (expected 2)
(bluesky_2021_1) [17bmuser@bm17-bluesky ~]>
```

**Comment by prjemian** [comment]
This is the (`spec2ophyd`) code that needs attention:

```python
                # FIXME: `1/0/0` is a new case from 17BM
                unit, chan, = list(map(int, uc_str.split("/")))[:2]  # FIXME:
```

@mdwyman : Thanks for reporting this!

**Comment by prjemian** [comment]
NOTE: `spec2ophyd` has no unit tests at this time.  Time to start.
