### ISSUE TITLE
findpv() can raise exceptions

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#509]
`findpv()` works fine but can report on uninitialized area detector plugins during the initial indexing operation, such as:

```python
In [1]: findpv("adsky:HDF1:FilePath_RBV")
Subscription value callback exception (EpicsSignal(read_pv='adsky:image1:ArrayData', name='adsimdet_image_array_data', parent='adsimdet_image', value=array([], dtype=uint8), timestamp=631152000.0, auto_monitor=True, string=False, write_pv='adsky:image1:ArrayData', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/home/mintadmin/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/device.py", line 223, in __get__
    return instance._signals[self.attr]
KeyError: 'shaped_image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mintadmin/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/signal.py", line 608, in _derived_value_callback
    value = self.inverse(value)
  File "/home/mintadmin/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/areadetector/base.py", line 107, in inverse
    raise RuntimeError(f"Invalid array size {self.derived_shape}")
RuntimeError: Invalid array size (0, 0, 0)
Out[1]: {'read': ['adsimdet.hdf1.file_path'], 'write': []}

In [2]: findpv("adsky:HDF1:FilePath_RBV")
Out[2]: {'read': ['adsimdet.hdf1.file_path'], 'write': []}

In [3]: findpv("sky:m1.RBV")
Out[3]: {'read': ['m1.user_readback'], 'write': []}

```

_Originally posted by @prjemian in https://github.com/BCDA-APS/apstools/issues/496#issuecomment-798807967_

**Comment by prjemian** [comment]
This is proving difficult to reproduce.  The exception trace originates from ophyd and does not identify where in `apstools.utils` called the ophyd code that raised the `KeyError` exception.

This looks like a timing issue before the device has connected fully and needs more examination.

**Comment by prjemian** [comment]
Found a way to reproduce.  Using the ADSimDetector provided in a docker container, interface with ophyd.SimDetector and ophyd.HDF5Plugin and the problem is found.  When using ophyd.areadetector.plugins.HDF5Plugin_V34, the problem is not found.

The problem arises when a Component is specified but the PV does not connect.  In this case, the area detector version changed and the PV, supported in a previous version, has been dropped from the database.

**Comment by prjemian** [comment]
This device exposes the problem:

```python
class MyCam(ophyd.SimDetectorCam):
    pool_max_buffers = None


class MyHDF5Plugin(
    ophyd.areadetector.filestore_mixins.FileStoreHDF5IterativeWrite,
    # ophyd.areadetector.plugins.HDF5Plugin_V34
    ophyd.HDF5Plugin
):
    pass


class MyFixedImagePlugin(ophyd.ImagePlugin):
    pool_max_buffers = None


class MyDetector(ophyd.SimDetector):
    cam = ophyd.ADComponent(MyCam, "cam1:")
    hdf1 = ophyd.ADComponent(
        MyHDF5Plugin,
        "HDF1:",
        write_path_template=AD_IOC_PATH,
        read_path_template=BLUESKY_PATH,
    )
    image = ophyd.ADComponent(MyFixedImagePlugin, "image1:")
```

**Comment by prjemian** [comment]
The problem to be solved with `findpv()` is how it handles this situation.  The underlying problem is one requiring different versions of the ophyd support for area detectors.

**Comment by MarkRivers** [comment]
> The underlying problem is one requiring different versions of the ophyd support for area detectors.

ophyd could be testing the version of ADCore to determine what PVs are present, it should not require a different version of the ophyd support.  The version is in the $(P)$(R)ADCoreVersion_RBV record, which exists for all detectors and plugins.

**Comment by MarkRivers** [comment]
Employing findpv() to detect the missing PV may pay a performance penalty, if it requires waiting for a Channel Access search timeout.

**Comment by prjemian** [comment]
I agree that ophyd's API with area detector should become more robust.  The ophyd structure is built before the PVs are connected.  The difficulty is to make those classes reconfigure themselves *before* they connect.

**Comment by prjemian** [comment]
The performance penalty is incurred during the cross-referencing phase.  Likely, this is done only once, after all the devices have been defined.  I'm looking at that code now.  The problem is triggered when asking about a signal for which no PV exists: https://github.com/BCDA-APS/apstools/blob/07517ddd82324f9577280e77a46bde1cf1341946/apstools/utils.py#L2409

Perhaps there is a different way to get the information without requiring the EpicsSignal to be connected?  That's my goal now.  There is no need (of `findname()` or `findpv()`) to ensure the EpicsSignal is actually connected to the IOC.

**Comment by prjemian** [comment]
At least, can trap the exception and log it, then continue.

## Device with default plugin version (many PVs no longer available)

```python
class MyHDF5Plugin(
    ophyd.areadetector.filestore_mixins.FileStoreHDF5IterativeWrite,
    # ophyd.areadetector.plugins.HDF5Plugin_V34
    ophyd.HDF5Plugin
):
    pass
```

<details>

```python
(base) prjemian@poof ~/.../BCDA-APS/apstools $ source /home/prjemian/Apps/anaconda/bin/activate
(base) prjemian@poof ~/.../BCDA-APS/apstools $ conda activate bluesky_2021_1
(bluesky_2021_1) prjemian@poof ~/.../BCDA-APS/apstools $ /home/prjemian/Apps/anaconda/envs/bluesky_2021_1/bin/python /home/prjemian/Documents/projects/BCDA-APS/apstools/tests/debug_findpv.py
Exception while getting object 'simdet.hdf1.file_number_sync': (adsky:HDF1:FileNumber_Sync could not connect within 1.0-second timeout.)
Exception while getting object 'simdet.hdf1.file_number_write': (adsky:HDF1:FileNumber_write could not connect within 1.0-second timeout.)
Exception while getting object 'simdet.hdf1.pool_max_buffers': (adsky:HDF1:PoolMaxBuffers could not connect within 1.0-second timeout.)
Subscription value callback exception (EpicsSignal(read_pv='adsky:image1:ArrayData', name='simdet_image_array_data', parent='simdet_image', value=array([], dtype=uint8), timestamp=631152000.0, auto_monitor=False, string=False, write_pv='adsky:image1:ArrayData', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/home/prjemian/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/home/prjemian/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/signal.py", line 608, in _derived_value_callback
    value = self.inverse(value)
  File "/home/prjemian/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/areadetector/base.py", line 107, in inverse
    raise RuntimeError(f"Invalid array size {self.derived_shape}")
RuntimeError: Invalid array size (0, 0, 0)
Subscription value callback exception (EpicsSignal(read_pv='adsky:image1:ArrayData', name='simdet_image_array_data', parent='simdet_image', value=array([], dtype=uint8), timestamp=631152000.0, auto_monitor=False, string=False, write_pv='adsky:image1:ArrayData', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/home/prjemian/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/device.py", line 223, in __get__
    return instance._signals[self.attr]
KeyError: 'shaped_image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prjemian/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/home/prjemian/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/signal.py", line 608, in _derived_value_callback
    value = self.inverse(value)
  File "/home/prjemian/Apps/anaconda/envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/areadetector/base.py", line 107, in inverse
    raise RuntimeError(f"Invalid array size {self.derived_shape}")
RuntimeError: Invalid array size (0, 0, 0)
apstools.utils.findpv(f"{AD_IOC_PREFIX}image1:ArrayData", ns=ns) = {'read': ['simdet.image.array_data'], 'write': ['simdet.image.array_data']}
apstools.utils.findpv(f"{AD_IOC_PREFIX}HDF1:FilePath_RBV", ns=ns) = {'read': ['simdet.hdf1.file_path'], 'write': []}
apstools.utils.findpv(f"{AD_IOC_PREFIX}cam1:Acquire", ns=ns) = {'read': [], 'write': ['simdet.cam.acquire']}
apstools.utils.findpv(f"{GP_IOC_PREFIX}m1.RBV", ns=ns) = {'read': ['gpm1.user_readback'], 'write': []}
apstools.utils.findname(gpm1.user_setpoint.name, ns=ns) = 'm1.user_setpoint'
apstools.utils.findname("m1_user_setpoint", ns=ns) = None
apstools.utils.findname(simdet.cam.acquire.name, ns=ns) = 'simdet.cam.acquire'
apstools.utils.findname("simdet_hdf1_array_size", ns=ns) = 'simdet.hdf1.array_size'
apstools.utils.findname("simdet_image_dim1_sa", ns=ns) = 'simdet.image.array_size.dim1_sa'
apstools.utils.findname("simdet_cam_peak_width_peak_width_y", ns=ns) = 'simdet.cam.peak_width.peak_width_y'
(bluesky_2021_1) prjemian@poof ~/.../BCDA-APS/apstools $ 
```

</details>



## Device with newer plugin version 

```python
class MyHDF5Plugin(
    ophyd.areadetector.filestore_mixins.FileStoreHDF5IterativeWrite,
    ophyd.areadetector.plugins.HDF5Plugin_V34
    # ophyd.HDF5Plugin
):
    pass

```

<details>

```python
(bluesky_2021_1) prjemian@poof ~/.../BCDA-APS/apstools $ /home/prjemian/Apps/anaconda/envs/bluesky_2021_1/bin/python /home/prjemian/Documents/projects/BCDA-APS/apstools/tests/debug_findpv.py
```

</details>


Either way, an exception trace will come from any subscription thread that has not yet received an image array (not been warmed up).  But at least `findpv()` and `findname()` will complete without stopping execution.
