### ISSUE TITLE
publish on conda-forge

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#670]
Publish this package on conda-forge.  See [spec2nexus](https://github.com/prjemian/spec2nexus/issues/246) for an example.

* [x] Fork [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes)
* [x] Create a new branch from the staged-recipes master branch.
* [x] Add a new conda recipe in a new "recipes/[your-package-name]" directory. There is an example of a well-written recipe in "recipes/example" you can copy. [Further guidance on writing good recipes. You can also test the recipe locally.](https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-recipe-meta-yaml)
* [x] Propose the change as a pull request. Your recipe will automatically be built on Windows, Linux, and OSX to test that it works, but the distribution will not yet be available on the conda-forge channel.
* [x] Once the recipe is ready it will be merged and a new "feedstock" repository will automatically be created for the recipe. The build and upload processes take place in the feedstock, and once complete the package will be available on the conda-forge channel.

**Comment by prjemian** [comment]
Not convinced v1.6.2 is ready for conda-forge.  Removing the problem entry points to test remainder of the build.

<details>
<summary>Problems</summary>

## workflow

```yaml
build:
  entry_points:
    - bluesky_snapshot = apstools.snapshot.application:snapshot_cli
    - bluesky_snapshot_viewer = apstools.snapshot.application:snapshot_gui
    - spec2ophyd = apstools.migration.spec2ophyd:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<3.10
  run:
    - area-detector-handlers
    - bluesky >=1.6.2
    - databroker >=1.2.4,<=1.2.5
    - databroker-pack
    - h5py
    - numpy
    - openpyxl
    - ophyd >=1.5.1
    - pint
    - pyepics >=3.4.2
    - pyresttable
    - python >=3.6,<3.10
    - spec2nexus >=2021.1.7
    - tk
    - xlrd

test:
  imports:
    - apstools
  commands:
    - pip check
    - bluesky_snapshot --help
    - bluesky_snapshot_viewer --help
    - spec2ophyd --help
  requires:
    - pip
```

### linux_64 failure

> + bluesky_snapshot --help

```
Traceback (most recent call last):
  File "/home/conda/staged-recipes/build_artifacts/apstools_1658949626637/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/bluesky_snapshot", line 6, in <module>
    from apstools.snapshot.application import snapshot_cli
  File "/home/conda/staged-recipes/build_artifacts/apstools_1658949626637/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.9/site-packages/apstools/snapshot/application.py", line 46, in <module>
    import tkinter as tk
  File "/home/conda/staged-recipes/build_artifacts/apstools_1658949626637/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libX11.so.6: cannot open shared object file: No such file or directory
```

### osx_64 failure

> + bluesky_snapshot_viewer --help

```
Traceback (most recent call last):
  File "/Users/runner/mambaforge/conda-bld/apstools_1658949764506/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/intake/catalog/base.py", line 350, in __getattr__
    return self[item]  # triggers reload_on_change
  File "/Users/runner/mambaforge/conda-bld/apstools_1658949764506/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/intake/catalog/base.py", line 423, in __getitem__
    raise KeyError(key)
KeyError: 'mongodb_config'
```

### win_64 failure

> bluesky_snapshot_viewer --help

```
Traceback (most recent call last):
  File "C:\bld\apstools_1658949732916\_test_env\lib\site-packages\intake\catalog\base.py", line 350, in __getattr__
    return self[item]  # triggers reload_on_change
  File "C:\bld\apstools_1658949732916\_test_env\lib\site-packages\intake\catalog\base.py", line 423, in __getitem__
    raise KeyError(key)
KeyError: 'mongodb_config'
```

</details>

**Comment by prjemian** [comment]
V1.6.2 is not ready for `conda-forge`.  It has [configuration for `noarch`](https://github.com/prjemian/staged-recipes/blob/01c94e6f2245a77deb6f5dca5a72ae8e37ec7371/recipes/apstools/meta.yaml#L15) yet this problem:

```
2022-07-27T21:39:04.0370025Z    INFO (apstools): Interpreted package 'apstools' is interpreted by 'python'
2022-07-27T21:39:04.1945290Z [noarch_python] Noarch package contains binary script: bluesky_snapshot_viewer.exe
2022-07-27T21:39:08.9276087Z ##[error]Cmd.exe exited with code '1'.
```

**Comment by prjemian** [comment]
In the end, removed the `noarch` specification from the conda-forge recipe.

**Comment by prjemian** [comment]
https://github.com/conda-forge/staged-recipes/pull/19839

**Comment by prjemian** [comment]
Consult https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html

**Comment by prjemian** [comment]
Also: https://docs.conda.io/projects/conda-build/en/latest/concepts/recipe.html

**Comment by prjemian** [comment]
To restrict build to just linux, [(from)](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#skipping-builds):

```yaml
build:
  skip: True  # [not linux]
```

note the double-negative

**Comment by prjemian** [comment]
references to old publishing channel(s):

```bash
(bluesky_2022_3) prjemian@zap:~/.../BCDA-APS/apstools$ git grep aps-anl-
CHANGES.rst:change, users will be able to ``conda install apstools -c aps-anl-tag`` on
README.md:[![conda](https://anaconda.org/aps-anl-tag/apstools/badges/version.svg)](https://anaconda.org/aps-anl-tag/apstools)
docs/source/install.rst:    $ conda install -c aps-anl-tag apstools
packaging.md:* [*aps-anl-tag*](https://anaconda.org/aps-anl-tag) : all releases starting 2021-11-24
packaging.md:* [*aps-anl-dev*](https://anaconda.org/aps-anl-dev) : anything else, such as: pre-release, release candidates, or testing purposes
```

- [ ] change the badge link
- [ ] update the install command
- [ ] delete `packaging.md`

**Comment by prjemian** [comment]
... waiting on conda-forge to approve the new recipe before the badge can be updated

**Comment by prjemian** [comment]
Feedstock: https://github.com/conda-forge/apstools-feedstock
