### ISSUE TITLE
drop Py3.7 per NEP29

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#673]
The NumPy package has a posted deprecation policy for minimum Python version in [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html).  Notably, the NumPy deprecation policy states:

date | Python version | NumPy version
-- | -- | --
Jun 21, 2022 | 3.8+ | 1.20+

**Comment by prjemian** [comment]
And add 3.10

**Comment by prjemian** [comment]
Py3.8 workflow failed.  Same problem seen in Py3.9 & Py3.10 workflows. Package installation succeeded but databorker/intake/mongoquery/collections failed when installing requisite test catalogs due to this problem:

```
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/mongoquery/__init__.py", line 7, in <module>
    from collections import Sequence, Mapping
ImportError: cannot import name 'Sequence' from 'collections' (/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/collections/__init__.py)
```

<details>
<summary>Error from Py3.10 workflow</summary>

```

Run ./resources/unpack.sh
  ./resources/unpack.sh
  shell: /usr/bin/bash -l {0}
  env:
    MAMBA_ROOT_PREFIX: /home/runner/micromamba
    MAMBA_EXE: /home/runner/micromamba-bin/micromamba
/home/runner/work/apstools/apstools/resources/apstools_test.zip
Archive:  /home/runner/work/apstools/apstools/resources/apstools_test.zip
  inflating: /tmp/apstools_test/catalog.yml  
   creating: /tmp/apstools_test/documents/
  inflating: /tmp/apstools_test/documents/04faecb3-7c8c-448b-9cf6-dc39c6f63b46.msgpack  
  inflating: /tmp/apstools_test/documents/0a87c465-d2d6-4b88-a9b8-dbbb2649027f.msgpack  
  inflating: /tmp/apstools_test/documents/0e8188e9-e317-4229-bb19-61249a820f94.msgpack  
  inflating: /tmp/apstools_test/documents/0fff7635-2dd3-4bc9-9b3a-a6449964140d.msgpack  
  inflating: /tmp/apstools_test/documents/142ff295-f395-455c-9a48-38d1a8f1770e.msgpack  
  inflating: /tmp/apstools_test/documents/21b9df0b-196b-4011-9a5a-d678f829746a.msgpack  
  inflating: /tmp/apstools_test/documents/22db8584-88d5-4ad4-b0a9-effc46d8e737.msgpack  
  inflating: /tmp/apstools_test/documents/2551749e-4fde-4f68-ba9e-16209529aabe.msgpack  
  inflating: /tmp/apstools_test/documents/2c29afa3-8b1e-4276-aa58-58b3c3bf66a1.msgpack  
  inflating: /tmp/apstools_test/documents/2edf5d04-8334-4592-ae83-909aa2c3df4b.msgpack  
  inflating: /tmp/apstools_test/documents/389cf146-5184-4ac6-b700-aa82f283609c.msgpack  
  inflating: /tmp/apstools_test/documents/3d48254d-4341-4aeb-b87e-9c35b1564e9a.msgpack  
  inflating: /tmp/apstools_test/documents/3e89a55c-d972-4271-a2b7-4e5d8bf74dab.msgpack  
  inflating: /tmp/apstools_test/documents/468d2cb6-38e7-4fb2-a172-00f2c293ddf0.msgpack  
  inflating: /tmp/apstools_test/documents/49dce8d9-8d52-4fe1-9d3b-8a72fce273c3.msgpack  
  inflating: /tmp/apstools_test/documents/4b602c7d-16aa-4c38-93a4-3b0b8cf1e63c.msgpack  
  inflating: /tmp/apstools_test/documents/4d41c06d-24ba-4bd2-8f46-f130601c34df.msgpack  
  inflating: /tmp/apstools_test/documents/50cd05b1-536c-4254-8d95-8e4180ab6486.msgpack  
  inflating: /tmp/apstools_test/documents/589516e2-0bd6-408e-a708-7ed1c4e9e440.msgpack  
  inflating: /tmp/apstools_test/documents/594d6893-11f5-45b8-96b9-7101ad04a6f3.msgpack  
  inflating: /tmp/apstools_test/documents/5e055ce1-b2cc-497c-997f-c2b53bb2d7b9.msgpack  
  inflating: /tmp/apstools_test/documents/616de318-d80c-46cc-97a9-4d7f88885a73.msgpack  
  inflating: /tmp/apstools_test/documents/64d4ed40-e0de-4801-9d4c-64317b5b1206.msgpack  
  inflating: /tmp/apstools_test/documents/67b7ef3c-377b-4009-844e-62148de6a2c3.msgpack  
  inflating: /tmp/apstools_test/documents/75f68f4e-984b-4a46-92f3-caa3808b7f58.msgpack  
  inflating: /tmp/apstools_test/documents/7ef69ea5-08ec-4649-abb2-f2989ec480e8.msgpack  
  inflating: /tmp/apstools_test/documents/82b4f54b-57f3-46bc-ae27-7414af79ebc6.msgpack  
  inflating: /tmp/apstools_test/documents/837ffac5-268f-4c78-8508-d20187d4ad4e.msgpack  
  inflating: /tmp/apstools_test/documents/88c928a4-08af-4fba-95c6-b98956e94f07.msgpack  
  inflating: /tmp/apstools_test/documents/98e20aa2-0050-4ea5-9343-f790b24f103a.msgpack  
  inflating: /tmp/apstools_test/documents/9a1eca71-d6ba-4127-81a7-2ab1ade34c48.msgpack  
  inflating: /tmp/apstools_test/documents/9af10cf3-8c6a-4290-816a-0a44183c3dd6.msgpack  
  inflating: /tmp/apstools_test/documents/a1729495-8661-4493-b882-38793241c4d3.msgpack  
  inflating: /tmp/apstools_test/documents/a729093c-1afe-45d1-bfd2-d86f9a32c66e.msgpack  
  inflating: /tmp/apstools_test/documents/a9dd3005-c3d4-4526-a1bd-c743be65d631.msgpack  
  inflating: /tmp/apstools_test/documents/aa62458e-7a76-4b51-9bac-1e63a58ec138.msgpack  
  inflating: /tmp/apstools_test/documents/af00d0db-eb7a-4023-8fe4-9413aabf6669.msgpack  
  inflating: /tmp/apstools_test/documents/af42771e-0cc8-4cac-a6a7-36d8c13f0323.msgpack  
  inflating: /tmp/apstools_test/documents/af73a062-e1a8-4873-981d-c982708d4e17.msgpack  
  inflating: /tmp/apstools_test/documents/b1e7f9a3-8d7b-42ef-a63d-7278a51db5d7.msgpack  
  inflating: /tmp/apstools_test/documents/b8fb07cd-0a68-4e9f-b79f-e5a6e32f4bec.msgpack  
  inflating: /tmp/apstools_test/documents/bb7e048f-00c1-4475-86c9-f94a873bf3c7.msgpack  
  inflating: /tmp/apstools_test/documents/c71dad31-fdfe-4d1f-b2e8-c4f19b1ca106.msgpack  
  inflating: /tmp/apstools_test/documents/c8c5597c-36d7-4c14-956d-4c1c9c90a864.msgpack  
  inflating: /tmp/apstools_test/documents/cf034c49-8dc6-4f46-ae8d-fd328dcab8ed.msgpack  
  inflating: /tmp/apstools_test/documents/cfde9e6d-8039-4933-b8f7-2a505b53dad4.msgpack  
  inflating: /tmp/apstools_test/documents/d9875a14-11cc-4340-90f7-b86e04348dcf.msgpack  
  inflating: /tmp/apstools_test/documents/ded2110e-db89-4f14-9291-004f910e2ef2.msgpack  
  inflating: /tmp/apstools_test/documents/e620aaab-99d4-4bb2-860a-107df4633e1c.msgpack  
  inflating: /tmp/apstools_test/documents/e8da2989-b742-4995-aa7b-e42489689670.msgpack  
  inflating: /tmp/apstools_test/documents/f0a39abb-d399-48f6-b7f5-81d760fc70d5.msgpack  
  inflating: /tmp/apstools_test/documents/f18346ae-e3e9-4500-95ea-7713d2b0366b.msgpack  
  inflating: /tmp/apstools_test/documents/ffb80ba7-22df-4ba1-b326-973cf42d9081.msgpack  
  inflating: /tmp/apstools_test/documents_manifest.txt  
Placed configuration file at /home/runner/.local/share/intake/databroker_unpack_apstools_test.yml
/home/runner/work/apstools/apstools/resources/usaxs_test.zip
Archive:  /home/runner/work/apstools/apstools/resources/usaxs_test.zip
  inflating: /tmp/usaxs_test/catalog.yml  
   creating: /tmp/usaxs_test/documents/
  inflating: /tmp/usaxs_test/documents/19965989-0a2a-44aa-aa06-c1248754e651.msgpack  
  inflating: /tmp/usaxs_test/documents/2ffe4d87-9f0c-464a-9d14-213ec71afaf7.msgpack  
  inflating: /tmp/usaxs_test/documents/3554003e-716d-41f3-9e57-873564ed3c84.msgpack  
  inflating: /tmp/usaxs_test/documents/555a6047-acd9-46a8-85b0-234986ae1323.msgpack  
  inflating: /tmp/usaxs_test/documents/6cfeb213-c4d6-4575-974d-43c5b7284395.msgpack  
  inflating: /tmp/usaxs_test/documents/99fe9e07-6a44-4834-856f-e48432fb01e5.msgpack  
  inflating: /tmp/usaxs_test/documents/b0aa6435-f058-42d9-9d46-54a18538417e.msgpack  
  inflating: /tmp/usaxs_test/documents/ddffefc1-f153-4716-b402-3ab2f141fb14.msgpack  
  inflating: /tmp/usaxs_test/documents/e5d2cbdc-c013-493c-a8cf-207a4f82d896.msgpack  
  inflating: /tmp/usaxs_test/documents/fdf496ee-827e-45cb-9e90-986b714554ea.msgpack  
  inflating: /tmp/usaxs_test/documents_manifest.txt  
Traceback (most recent call last):
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/bin/databroker-unpack", line 6, in <module>
    from databroker_pack.commandline.unpack import main
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/databroker_pack/__init__.py", line 6, in <module>
    from ._pack import *  # noqa
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/databroker_pack/_pack.py", line 10, in <module>
    import databroker.core
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/databroker/__init__.py", line 22, in <module>
    catalog = MergedCatalog([
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 833, in __init__
    super().__init__(*args, **kwargs)
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/base.py", line 101, in __init__
    self.force_reload()
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/base.py", line 159, in force_reload
    self._load()
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 837, in _load
    catalog._load()
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 810, in _load
    entry.reload()
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/base.py", line 164, in reload
    self.force_reload()
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/base.py", line 159, in force_reload
    self._load()
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 608, in _load
    self.parse(text)
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 684, in parse
    result = CatalogParser(data, context=context, getenv=self.getenv,
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 318, in __init__
    self._data = self._parse(data)
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 520, in _parse
    data_sources=self._parse_data_sources(data),
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 507, in _parse_data_sources
    obj = self._parse_data_source(name, source)
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 432, in _parse_data_source
    return self._parse_data_source_local(name, data)
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 477, in _parse_data_source_local
    return LocalCatalogEntry(catalog_dir=self._context['root'],
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 185, in __init__
    dr = get_plugin_class(driver)
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/source/__init__.py", line 103, in get_plugin_class
    if name in registry:
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/_collections_abc.py", line 825, in __contains__
    self[key]
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/utils.py", line 206, in __getitem__
    return self._registry[key]
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/source/__init__.py", line 26, in __getitem__
    self[item] = super().__getitem__(item).load()
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/entrypoints.py", line 79, in load
    mod = import_module(self.module_name)
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/databroker/_drivers/msgpack.py", line 8, in <module>
    from ..in_memory import BlueskyInMemoryCatalog
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/databroker/in_memory.py", line 5, in <module>
    from mongoquery import Query
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/mongoquery/__init__.py", line 7, in <module>
    from collections import Sequence, Mapping
ImportError: cannot import name 'Sequence' from 'collections' (/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/collections/__init__.py)
Traceback (most recent call last):
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/bin/databroker-pack", line 6, in <module>
    from databroker_pack.commandline.pack import main
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/databroker_pack/__init__.py", line 6, in <module>
    from ._pack import *  # noqa
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/databroker_pack/_pack.py", line 10, in <module>
    import databroker.core
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/databroker/__init__.py", line 22, in <module>
    catalog = MergedCatalog([
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 833, in __init__
    super().__init__(*args, **kwargs)
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/base.py", line 101, in __init__
    self.force_reload()
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/base.py", line 159, in force_reload
    self._load()
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 837, in _load
    catalog._load()
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 810, in _load
    entry.reload()
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/base.py", line 164, in reload
    self.force_reload()
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/base.py", line 159, in force_reload
    self._load()
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 608, in _load
    self.parse(text)
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 684, in parse
    result = CatalogParser(data, context=context, getenv=self.getenv,
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 318, in __init__
    self._data = self._parse(data)
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 520, in _parse
    data_sources=self._parse_data_sources(data),
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 507, in _parse_data_sources
    obj = self._parse_data_source(name, source)
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 432, in _parse_data_source
    return self._parse_data_source_local(name, data)
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 477, in _parse_data_source_local
    return LocalCatalogEntry(catalog_dir=self._context['root'],
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/catalog/local.py", line 185, in __init__
    dr = get_plugin_class(driver)
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/source/__init__.py", line 103, in get_plugin_class
    if name in registry:
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/_collections_abc.py", line 825, in __contains__
    self[key]
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/utils.py", line 206, in __getitem__
    return self._registry[key]
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/intake/source/__init__.py", line 26, in __getitem__
    self[item] = super().__getitem__(item).load()
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/entrypoints.py", line 79, in load
    mod = import_module(self.module_name)
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/databroker/_drivers/msgpack.py", line 8, in <module>
    from ..in_memory import BlueskyInMemoryCatalog
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/databroker/in_memory.py", line 5, in <module>
    from mongoquery import Query
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/mongoquery/__init__.py", line 7, in <module>
    from collections import Sequence, Mapping
ImportError: cannot import name 'Sequence' from 'collections' (/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/collections/__init__.py)
Error: Process completed with exit code 1.
```

</details>

**Comment by prjemian** [comment]
We've had recent successful runs, so it's time to compare versions

package | successful | failed | note(s)
--- | --- | --- | ---
databroker | 1.2.5 | 1.2.5 | 
databroker-pack | 0.3.0 | 0.3.0 | 
intake | 0.6.4 | 0.6.4 | 
mongoquery | 1.3.5 | 1.3.4 | **_Suspicious_**
collections | not reported | not reported | [Python standard library ](https://docs.python.org/3/library/collections.html)

**Comment by prjemian** [comment]
There are **_no differences_** in versions of all installed packages in the [successful](https://github.com/BCDA-APS/apstools/runs/7589211382?check_suite_focus=true) and [failed](https://github.com/BCDA-APS/apstools/runs/7592869686?check_suite_focus=true) runs.

**Comment by prjemian** [comment]
It's the unpack test libraries step, same files for any workflow.  Can this be done in a previous job and cached in the workflow?

**Comment by prjemian** [comment]
```bash
micromamba create -n test python pip
micromamba activate test
pip install git+https://github.com/bluesky/databroker-pack.git@master
cd resources
./unpack.sh
```

```
~/Documents/projects/BCDA-APS/apstools/resources/apstools_test.zip
Archive:  ~/Documents/projects/BCDA-APS/apstools/resources/apstools_test.zip
Placed configuration file at ~/.local/share/intake/databroker_unpack_apstools_test.yml
~/Documents/projects/BCDA-APS/apstools/resources/usaxs_test.zip
Archive:  ~/Documents/projects/BCDA-APS/apstools/resources/usaxs_test.zip
Placed configuration file at ~/.local/share/intake/databroker_unpack_usaxs_test.yml
```

**Comment by prjemian** [comment]
Also various databroker catalog directories in `/tmp`.

**Comment by prjemian** [comment]
Root cause is the version of [mongoquery](https://github.com/kapouille/mongoquery).  This error:

```
  File "/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/site-packages/mongoquery/__init__.py", line 7, in <module>
    from collections import Sequence, Mapping
ImportError: cannot import name 'Sequence' from 'collections' (/home/runner/micromamba/envs/anaconda-test-env-py-3.8/lib/python3.10/collections/__init__.py)
```

is from [mongoquery 1.3.5](https://github.com/kapouille/mongoquery/blob/1.3.5/mongoquery/__init__.py#L7):

```py
from collections import Sequence, Mapping
```

and replaced in [mongoquery >=1.3.6](https://github.com/kapouille/mongoquery/blob/1.3.6/mongoquery/__init__.py#L7):

```py
from collections.abc import Sequence, Mapping
```

**Comment by prjemian** [comment]
But the [newest version available](https://anaconda.org/search?q=mongoquery) is 1.3.6 on the `nsls2forge` channel.  Add that channel.

**Comment by prjemian** [comment]
And, the `channel-priority: flexible` feature is broken in [v12 of the actions workflow](https://github.com/mamba-org/provision-with-micromamba/tree/v12).  Always installs with `--strict-channel-priority` command line option in the [`index.js`](https://github.com/mamba-org/provision-with-micromamba/blob/v12/index.js#L279) file.  Here's the actions workflow to use now:

```yaml
    - name: Create Python ${{ matrix.python-version }} environment
      uses: mamba-org/provision-with-micromamba@main
      # use main branch to enable choice of channel-priority
```

**Comment by prjemian** [comment]
Weird.  Just a failure due to `test_NXWriter_make_file_name()` involving `None` instead of an integer.  This has not failed before.

**Comment by prjemian** [comment]
```
        with pytest.raises(TypeError) as exinfo:
            callback.make_file_name()
>       assert (
            "an integer is required (got type NoneType)"
            in str(exinfo.value)
        )
E       assert 'an integer is required (got type NoneType)' in "'NoneType' object cannot be interpreted as an integer"
E        +  where "'NoneType' object cannot be interpreted as an integer" = str(TypeError("'NoneType' object cannot be interpreted as an integer"))
E        +    where TypeError("'NoneType' object cannot be interpreted as an integer") = <ExceptionInfo TypeError("'NoneType' object cannot be interpreted as an integer") tblen=2>.value

/home/runner/work/apstools/apstools/apstools/callbacks/tests/test_filewriter.py:168: AssertionError
```

**Comment by prjemian** [comment]
The string from the exception is not the string that is expected.
