### ISSUE TITLE
BUG: unit test failure in CI

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/apstools#899]
unit test failure in CI unrelated to PR #898

```py
2023-12-27T17:34:10.7032169Z apstools/devices/tests/test_flyer_motor_scaler.py::test_ScalerMotorFlyer[0-0-1-2-0.1-9-0] FAILED [ 14%]
2023-12-27T17:34:10.7033120Z 
2023-12-27T17:34:10.7033392Z =================================== FAILURES ===================================
2023-12-27T17:34:10.7034444Z ____________________ test_ScalerMotorFlyer[0-0-1-2-0.1-9-0] ____________________
2023-12-27T17:34:10.7035049Z 
2023-12-27T17:34:10.7035469Z start = 0, finish = 0, fly_time = 1, fly_time_pad = 2, period = 0.1, n_keys = 9
2023-12-27T17:34:10.7036274Z n_data = 0
2023-12-27T17:34:10.7036509Z 
2023-12-27T17:34:10.7036695Z     @pytest.mark.parametrize(
2023-12-27T17:34:10.7037426Z         "start, finish, fly_time, fly_time_pad, period, n_keys, n_data",
2023-12-27T17:34:10.7038509Z         [
2023-12-27T17:34:10.7039129Z             [-1, 1, None, None, None, NUM_READING_KEYS, 10],
2023-12-27T17:34:10.7040028Z             [-1, 1, 2, 2, 1, NUM_READING_KEYS, 2],
2023-12-27T17:34:10.7040771Z             [-1, 1, 1, 2, 0.1, NUM_READING_KEYS, 10],
2023-12-27T17:34:10.7041424Z             [0, 0, 1, 2, 0.1, NUM_READING_KEYS, 0],
2023-12-27T17:34:10.7042179Z             [1, -1, 1, 2, 0.1, NUM_READING_KEYS, 10],
2023-12-27T17:34:10.7042758Z         ],
2023-12-27T17:34:10.7043070Z     )
2023-12-27T17:34:10.7043798Z     def test_ScalerMotorFlyer(start, finish, fly_time, fly_time_pad, period, n_keys, n_data):
2023-12-27T17:34:10.7044729Z         flyer = ScalerMotorFlyer(
2023-12-27T17:34:10.7045677Z             scaler1, m1, start, finish, name="flyer", fly_time=fly_time, fly_time_pad=fly_time_pad, period=period
2023-12-27T17:34:10.7046627Z         )
2023-12-27T17:34:10.7047044Z         assert isinstance(flyer, ScalerMotorFlyer)
2023-12-27T17:34:10.7047728Z         assert hasattr(flyer, "action_exception")
2023-12-27T17:34:10.7048281Z     
2023-12-27T17:34:10.7048622Z >       uids = RE(bp.fly([flyer]))
2023-12-27T17:34:10.7048973Z 
2023-12-27T17:34:10.7049619Z /home/runner/work/apstools/apstools/apstools/devices/tests/test_flyer_motor_scaler.py:92: 
2023-12-27T17:34:10.7050755Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2023-12-27T17:34:10.7054038Z /home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/run_engine.py:903: in __call__
2023-12-27T17:34:10.7055701Z     plan_return = self._resume_task(init_func=_build_task)
2023-12-27T17:34:10.7057468Z /home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/run_engine.py:1042: in _resume_task
2023-12-27T17:34:10.7058924Z     raise exc
2023-12-27T17:34:10.7060478Z /home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/run_engine.py:1672: in _run
2023-12-27T17:34:10.7061790Z     raise err
2023-12-27T17:34:10.7063129Z /home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/run_engine.py:1507: in _run
2023-12-27T17:34:10.7064748Z     msg = self._plan_stack[-1].throw(stashed_exception or resp)
2023-12-27T17:34:10.7066320Z /home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/plans.py:1977: in fly
2023-12-27T17:34:10.7067584Z     yield from bps.collect(flyer)
2023-12-27T17:34:10.7069031Z /home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/plan_stubs.py:696: in collect
2023-12-27T17:34:10.7070872Z     return (yield Msg('collect', obj, stream=stream, return_payload=return_payload, name=name))
2023-12-27T17:34:10.7073574Z /home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/run_engine.py:1592: in _run
2023-12-27T17:34:10.7074900Z     new_response = await coro(msg)
2023-12-27T17:34:10.7076380Z /home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/run_engine.py:2116: in _collect
2023-12-27T17:34:10.7077747Z     return (await current_run.collect(msg))
2023-12-27T17:34:10.7079235Z /home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/bundlers.py:998: in collect
2023-12-27T17:34:10.7080547Z     payload = await self._collect_events(
2023-12-27T17:34:10.7082094Z /home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/bundlers.py:886: in _collect_events
2023-12-27T17:34:10.7083724Z     await self.emit(DocumentNames.event_page, pack_event_page(*event_list))
2023-12-27T17:34:10.7084765Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2023-12-27T17:34:10.7085421Z 
2023-12-27T17:34:10.7085582Z events = ()
2023-12-27T17:34:10.7085816Z 
2023-12-27T17:34:10.7086200Z     def pack_event_page(*events: Event) -> EventPage:
2023-12-27T17:34:10.7086842Z         """
2023-12-27T17:34:10.7087734Z         Transform one or more Event documents into an EventPage document.
2023-12-27T17:34:10.7088541Z     
2023-12-27T17:34:10.7088897Z         Parameters
2023-12-27T17:34:10.7089362Z         ----------
2023-12-27T17:34:10.7089783Z         *event : dicts
2023-12-27T17:34:10.7090275Z             any number of Event documents
2023-12-27T17:34:10.7090832Z     
2023-12-27T17:34:10.7091176Z         Returns
2023-12-27T17:34:10.7091603Z         -------
2023-12-27T17:34:10.7092010Z         event_page : dict
2023-12-27T17:34:10.7092463Z         """
2023-12-27T17:34:10.7092840Z         if not events:
2023-12-27T17:34:10.7093293Z >           raise ValueError(
2023-12-27T17:34:10.7094003Z                 "The pack_event_page() function was called with empty *args. "
2023-12-27T17:34:10.7095047Z                 "Cannot create an EventPage from an empty collection of Events "
2023-12-27T17:34:10.7096206Z                 "because the 'descriptor' field in an EventPage cannot be NULL."
2023-12-27T17:34:10.7096989Z             )
2023-12-27T17:34:10.7098907Z E           ValueError: The pack_event_page() function was called with empty *args. Cannot create an EventPage from an empty collection of Events because the 'descriptor' field in an EventPage cannot be NULL.
2023-12-27T17:34:10.7100531Z 
2023-12-27T17:34:10.7101643Z /home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/event_model/__init__.py:2616: ValueError
2023-12-27T17:34:10.7103244Z ------------------------------ Captured log call -------------------------------
2023-12-27T17:34:10.7104066Z ERROR    bluesky:run_engine.py:1671 Run aborted
2023-12-27T17:34:10.7104726Z Traceback (most recent call last):
2023-12-27T17:34:10.7106297Z   File "/home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/run_engine.py", line 1507, in _run
2023-12-27T17:34:10.7107937Z     msg = self._plan_stack[-1].throw(stashed_exception or resp)
2023-12-27T17:34:10.7108707Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27T17:34:10.7110297Z   File "/home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/plans.py", line 1977, in fly
2023-12-27T17:34:10.7111855Z     yield from bps.collect(flyer)
2023-12-27T17:34:10.7113472Z   File "/home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/plan_stubs.py", line 696, in collect
2023-12-27T17:34:10.7115409Z     return (yield Msg('collect', obj, stream=stream, return_payload=return_payload, name=name))
2023-12-27T17:34:10.7116470Z             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27T17:34:10.7118145Z   File "/home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/run_engine.py", line 1592, in _run
2023-12-27T17:34:10.7119808Z     new_response = await coro(msg)
2023-12-27T17:34:10.7120329Z                    ^^^^^^^^^^^^^^^
2023-12-27T17:34:10.7121767Z   File "/home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/run_engine.py", line 2116, in _collect
2023-12-27T17:34:10.7123085Z     return (await current_run.collect(msg))
2023-12-27T17:34:10.7123655Z             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27T17:34:10.7125180Z   File "/home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/bundlers.py", line 998, in collect
2023-12-27T17:34:10.7126590Z     payload = await self._collect_events(
2023-12-27T17:34:10.7127213Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27T17:34:10.7128888Z   File "/home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/bluesky/bundlers.py", line 886, in _collect_events
2023-12-27T17:34:10.7130643Z     await self.emit(DocumentNames.event_page, pack_event_page(*event_list))
2023-12-27T17:34:10.7131605Z                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-27T17:34:10.7133416Z   File "/home/runner/micromamba/envs/anaconda-test-env-py-3.11/lib/python3.11/site-packages/event_model/__init__.py", line 2616, in pack_event_page
2023-12-27T17:34:10.7135134Z     raise ValueError(
2023-12-27T17:34:10.7137144Z ValueError: The pack_event_page() function was called with empty *args. Cannot create an EventPage from an empty collection of Events because the 'descriptor' field in an EventPage cannot be NULL.
```

_Originally posted by @prjemian in https://github.com/BCDA-APS/apstools/issues/898#issuecomment-1870506296_

**Comment by prjemian** [comment]
Suspect this new CI failure is due to changes in an upstream package.

**Comment by prjemian** [comment]
Closing as duplicate since this work will be handled as part of #763.
